version: '3.8'
services:
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=netology
  server:
    command: sh -c "python manage.py migrate && gunicorn stocks_products.wsgi -b 0.0.0.0:8000"
    image: stocksproducts
    ports:
      - 8000:8000
    depends_on:
      - db
  nginx:
    image: stocksproducts2
    ports:
      - 80:80
    depends_on:
      - server
      - db